version: '3.8'

services:
  server:
    container_name: blockvector-server
    image: blockmaker/blockvector:latest
    ports:
      - "8080:8080"
    environment:
      - BLOCKVECTOR_LOG_LEVEL=INFO
      - BLOCKVECTOR_PORT=:8080
      - BLOCKVECTOR_FILENAME=/app/data/blockvector.bin
      - BLOCKVECTOR_DIMENSIONS=1536
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - blockvector-net

  prometheus:
    image: prom/prometheus:latest
    container_name: blockvector-prometheus
    volumes:
      - ./deployments/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - blockvector-net

  grafana:
    image: grafana/grafana:latest
    container_name: blockvector-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=blockmaker
    networks:
      - blockvector-net

  cli-generator:
    image: blockmakercompany/blockvector:latest
    container_name: blockvector-cli
    entrypoint: ["/app/blockvector-cli"]
    environment:
      - BLOCKVECTOR_FILENAME=/app/data/blockvector.bin
    volumes:
      - ./data:/app/data
    profiles:
      - setup
    networks:
      - blockvector-net

networks:
  blockvector-net:
    driver: bridge